<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
/** @var $celebrosAutocompleteHelper Celebros\AutoComplete\Helper\Data */
$celebrosAutocompleteHelper = $this->helper('Celebros\AutoComplete\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-title"><strong><?php echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           <?php if (!$celebrosAutocompleteHelper->isEnabled()) : ?>
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           <?php endif ?>
                           type="text"
                           name="<?php echo $helper->getQueryParamName() ?>"
                           value="<?php echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php echo __('Search entire store here...'); ?>"
                           class="input-text"
                           maxlength="<?php echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           />
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?php echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>

<?php if ($celebrosAutocompleteHelper->isEnabled()) : ?>
<script type="text/javascript">
    function onSelect(aParameter) {
        if ((aParameter["SelectedURL"] != "") && (aParameter["IsAutoComplete"])) {
            var sCmp = (aParameter["SelectedURL"].indexOf("?") == -1) ? "?" : "&";
            window.location = aParameter["SelectedURL"] + sCmp + "cmp=cel" + "&trigger=ac";
        } else if (window['UITemplateConfigurationMaster'] != undefined) {
            var e = jQueryCel.Event("keypress");
            e.which = 13; e.keyCode = 13;
            jQueryCel('#search').trigger(e);
            return false; 
        } else { 
            var targetLocation = "<?php echo $helper->getResultUrl() ?>?<?php echo $celebrosAutocompleteHelper->getQueryParamName() ?>=" + encodeURIComponent(aParameter["SelectedQuery"]);
            if (aParameter["IsAutoComplete"].toString().toLowerCase() == "true") targetLocation += "&Trigger=ac";
            window.location = targetLocation;
        }
    }
    CelebrosAutoComplete("<?php echo $celebrosAutocompleteHelper->getCustomerName()?>", "search",  onSelect, "<?php echo $celebrosAutocompleteHelper->getFrontendServerAddress()?>", "<?php echo $celebrosAutocompleteHelper->getScriptServerAddress()?>");
</script>
<?php endif ?>
