<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
/** @var $celHelper Celebros\AutoComplete\Helper\Data */
$celHelper = $this->helper(\Celebros\AutoComplete\Helper\Data::class);
?>
<?php if ($celHelper->isEnabled()): ?>
    <?php if ($cssUrl = $celHelper->getExternalCssUrl()): ?>
<link rel="stylesheet" type="text/css" media="all" href="<?= $block->escapeHtml($celHelper->getProtocol()) . '://' . $block->escapeUrl($cssUrl) ?>"/>
    <?php endif; ?>
<script type="text/javascript">
require(["jquery"], function (jQuery) {
    require(["jquery/ui"], function () {
        require(["<?= $block->escapeHtml($celHelper->getProtocol()) ?>://<?= $block->escapeUrl($celHelper->getScriptServerAddress()) ?>/AutoComplete/Scripts/CelebrosAutoCompleteV3e.js"], function() {
            CelebrosAutoCompleteV3(
                "<?= $block->escapeHtml($celHelper->getCustomerName()) ?>",
                "search",
                onSelect,
                "<?= $block->escapeUrl($celHelper->getFrontendServerAddress()) ?>",
                "<?= $block->escapeUrl($celHelper->getScriptServerAddress()) ?>",
                {
                    acShowType: "regular",
                    btnSearch: "search_button",
                    maxControl: "server"
                }
            );
        });
    });
});
function onSelect(aParameter) {
    if ((aParameter["SelectedURL"] != "") && (aParameter["IsAutoComplete"])) {
        var sCmp = (aParameter["SelectedURL"].indexOf("?") == -1) ? "?" : "&";
        window.location = aParameter["SelectedURL"] + sCmp + "cmp=cel" + "&trigger=ac";
    } else { 
        var targetLocation = "<?= $block->escapeUrl($helper->getResultUrl()) ?>?<?= $block->escapeHtml($celHelper->getQueryParamName()) ?>=" + encodeURIComponent(aParameter["SelectedQuery"]);
        if (aParameter["IsAutoComplete"].toString().toLowerCase() == "true") targetLocation += "&Trigger=ac";
        window.location = targetLocation;
    }
};
</script>
<?php endif ?>